# Generated by Django 6.0.7 on 2026-08-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('complement', models.CharField(blank=True, max_length=60, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=60, null=True)),
                ('town', models.CharField(blank=True, max_length=60, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('brief_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('area_facility', models.IntegerField(default=0)),
                ('area_land', models.IntegerField(default=0)),
                ('highlight', models.BooleanField(default=False)),
                ('square', models.CharField(blank=True, max_length=15, null=True)),
                ('lot', models.CharField(blank=True, max_length=15, null=True)),
                ('registration', models.CharField(blank=True, max_length=40, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=80, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('owner_fone1', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_fone2', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_fone3', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_fone4', models.CharField(blank=True, max_length=20, null=True)),
                ('parley', models.TextField(blank=True, null=True)),
                ('youtube', models.CharField(blank=True, max_length=20, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='properties/images/')),
                ('view_order', models.PositiveIntegerField(default=1)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.subcategory'),
        ),
    ]
